# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# variables defined in the `.env` file (same directory as this script) 

### Execute locally
POST http://localhost:7071/admin/functions/UpdateGeneralMemberCount
Content-Type: application/json

{}

### Execute remotely in the cloud
POST https://CbSlackStatsFunctions.azurewebsites.net/admin/functions/UpdateGeneralMemberCount
x-functions-key: {{$dotenv FUNCTIONSKEY}}
Content-Type: application/json

{}