name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**

env:
  AZURE_FUNCTIONAPP_NAME: CodingBlocksUptimeFunctions20240211151814
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src/CodingBlocksUptime.Functions/published
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  FUNCTIONS_PROJECT_FOLDER: src/CodingBlocksUptime.Functions
  SOLUTION_FILE: src/CodingBlocksUptime.sln

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.SOLUTION_FILE }}"
      - name: Build
        run: dotnet build "${{ env.SOLUTION_FILE }}" --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: Test
        run: dotnet test "${{ env.SOLUTION_FILE }}" --configuration ${{ env.CONFIGURATION }}
      - name: Publish
        run: dotnet publish "${{ env.FUNCTIONS_PROJECT_FOLDER }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.CodingBlocksUptimeFunctions20240211151814_D5A0 }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
